#!/bin/bash

### READ FROM DISC

echo "------------------"
echo "STARTING DISC COPY"
echo "------------------"
echo ""
DEV=$(lsblk -ndo NAME,TYPE | awk '$2=="rom"{print $1; exit}')
[ -z "/dev/$DEV" ] && {
    echo "No optical drive found."
    exit 1
}
DIR="/home/sprokkel/nas/SHARE/BACKUP"
SOURCE="$1"
STORE="/home/sprokkel/nas/SHARE/BACKUP"

if [ -z "$SOURCE" ]; then
    echo "Usage: $0 /dev/"$DEV""
    exit 1
fi

mapfile -t STARTS < <(
    xorriso -indev /dev/"$DEV" -toc 2>/dev/null |
    awk '/ISO session/ {print $6}' |
    tr -d ','
)

COUNT=${#STARTS[@]}

if [ "$COUNT" -eq 0 ]; then
    echo "No sessions found"
    eject /dev/"$DEV"
    exit 1
fi

for ((i=0; i<COUNT; i++))
do
    START=${STARTS[$i]}

    if [ $((i+1)) -lt "$COUNT" ]; then
        y=$((i + 1))
        echo ""
        echo "EXTRACTING SESSION - $y - TO HARD-DISK"
        echo ""
        NEXT=${STARTS[$((i+1))]}
        BLOCKS=$((NEXT - START))

        dd if="$SOURCE" \
           of="$STORE/bd-session-$((i+1)).iso" \
           bs=2048 \
           skip="$START" \
           count="$BLOCKS" \
           status=progress
    else
        echo "EXTRACTING SESSION - $((i+1)) - TO HARD-DISK"
        dd if="$SOURCE" \
           of="$STORE/bd-session-$((i+1)).iso" \
           bs=2048 \
           skip="$START" \
           status=progress
    fi
done


### WRITE TO DISC

echo "EJECTING SOURCE DISC"
eject /dev/"$DEV"
play /usr/share/sounds/freedesktop/stereo/complete.oga > /dev/null 2>&1

echo ""
echo "INSERT DESTINATION DISC"
echo "Press enter to continue"
read enter

shopt -s nullglob

FILES=("$DIR"/bd-session-*.iso)

if [ ${#FILES[@]} -eq 0 ]; then
    echo "No session ISO files found."
    exit 1
fi

printf "Found sessions:\n"
printf '  %s\n' "${FILES[@]}"
echo

for ISO in $(printf '%s\n' "${FILES[@]}" | sort -V)
do
    echo
    echo "================================================"
    echo "WRITING $(basename "$ISO")"
    echo "================================================"

    xorriso -as cdrecord \
        dev="/dev/$DEV" \
        -multi \
        "$ISO"

    if [ $? -ne 0 ]; then
        echo "Burn failed: $ISO"
        exit 1
    fi

    echo "Finished $(basename $ISO)"
done

echo
echo "All sessions written."
echo ""
echo "DISC COPY COMPLETED."
echo
echo "Removing session ISO files..."
rm -f /home/sprokkel/nas/SHARE/BACKUP/bd-session-*.iso
echo "Done."
echo ""
echo "SCRIPT COMPLETED, Ejecting Disc."
echo ""
eject "/dev/$DEV"
echo "Press enter to close."
read enter
