#!/bin/sh
echo "RUNNING BLURAY DISC DAEMON ..."
udisksctl monitor | while read -r line
do
    case "$line" in
        *"MediaAvailable:               true"*)
            pgrep -f gnome-terminal --title="Bluray Disc Sessions" -- /usr/local/bin/blustart >/dev/null 2>&1
            ;;
    esac
done
