#!/bin/sh
clear
blustop
sleep 3
clear
DEV=$(lsblk -ndo NAME,TYPE | awk '$2=="rom"{print $1; exit}')
[ -z "$DEV" ] && {
    echo "No optical drive found."
    exit 1
}
COUNTER=1
echo "------------------------"
echo "- BLURAY DISC SESSIONS -"
echo "------------------------"
echo ""
echo "- Reading Table Of Contents, Please Wait ..."
echo -n "- Reading ."
rm -f /tmp/.blulog
dvd+rw-mediainfo /dev/"$DEV" 2>/dev/null |
grep "Start" |
awk '{sub(/\*2KB$/, "", $4); print $4}' |
while read SECTOR
do
    LOOP=$(sudo losetup -f --show -r -o $((SECTOR * 2048)) /dev/"$DEV")

    LABEL=$(sudo isoinfo -d -i "$LOOP" 2>/dev/null |
            awk -F': ' '/Volume id:/ {print $2}')

    if [ -z "$LABEL" ] 
    then 
        LABEL="empty session"
    fi
    echo "Track Nr. $COUNTER | Start Sector: $SECTOR | Label: $LABEL" >> /tmp/.blulog
    echo -n "."
    sudo losetup -d "$LOOP"
    COUNTER=$((COUNTER + 1))
done
echo ""
echo ""
i=1
while [ $i -eq 1 ]
do
echo >> /tmp/.blulog
cat /tmp/.blulog
echo ""
echo -n "- "
blufree
#dvd+rw-mediainfo /dev/"$DEV" | grep Start || exit 1

echo ""
echo "- Type 'n' to create a 'New Session', or"
echo "- Type 'Start Sector Number' to 'Load a Session', or"
echo "- Type 'c' to 'COPY' the 'DISC', or"
echo "- Type 'm' to 'MOUNT' a 'DVD-VIDEO-DISC', or"
echo "- Type 'e' to 'Eject', or"
echo "- Type 'q' to 'Quit'."
echo ""
echo -n "Your Choice: "
read SECTOR
echo ""
if [ "$SECTOR" = "n" ]
then 
bluburn
rm -f /tmp/.blulog
break
exit 0
elif [ "$SECTOR" = "e" ]
then
rm -f /tmp/.blulog
eject /dev/"$DEV"
blustop
break
exit 0
elif [ "$SECTOR" = "q" ]
then
        rm -f /tmp/.blulog
        blustop
	break
	exit 0
elif [ "$SECTOR" = "c" ]
then
	blucopy /dev/"$DEV"
	break
	exit 0
elif [ "$SECTOR" = "m" ]
then
	udisksctl mount -b /dev/"$DEV"
	nautilus -w /run/media/"$USER"/ >/dev/null 2>&1 &
else
blustop
echo "CREATING LOOP DEVICE AS ROOT :"
LOOP=`sudo losetup -fP --show \
    -o $(($SECTOR*2048)) \
    /dev/"$DEV"`
echo "DONE"

echo -n "MOUNTING SESSION AS ROOT -> "
sudo mount -t iso9660 -o ro "$LOOP" /home/sprokkel/bluray/ || exit 1
echo "DONE"
echo ""
echo "---------------------"
echo "/home/sprokkel/bluray"
echo "---------------------"
echo ""
ls -ld /home/sprokkel/bluray/*
echo ""
play /usr/share/sounds/freedesktop/stereo/complete.oga > /dev/null 2>&1
echo "SCRIPT COMPLETED -> SESSION SECTOR $SECTOR = MOUNTED."
echo ""
nautilus -w /home/sprokkel/bluray & > /dev/null 2>&1
fi
done
