#!/bin/sh
clear
blustop
DEV=$(lsblk -ndo NAME,TYPE | awk '$2=="rom"{print $1; exit}')
[ -z "$DEV" ] && {
    echo "No optical drive found."
    exit 1
}
COUNTER=1
echo "--------------------"
echo "BLURAY DISC SESSIONS"
echo "--------------------"
echo ""
echo "Reading Table Of Contents:"
echo ""
dvd+rw-mediainfo /dev/"$DEV" |
grep "Start" |
awk '{sub(/\*2KB$/, "", $4); print $4}' |
while read SECTOR
do
    LOOP=$(sudo losetup -f --show -r -o $((SECTOR * 2048)) /dev/"$DEV")

    LABEL=$(sudo isoinfo -d -i "$LOOP" 2>/dev/null |
            awk -F': ' '/Volume id:/ {print $2}')

    if [ -z "$LABEL" ] 
    then 
        LABEL="End Of Disc"
    fi
    echo "Track Nr. $COUNTER | Start Sector: $SECTOR | Label: $LABEL"

    sudo losetup -d "$LOOP"
    COUNTER=$((COUNTER + 1))
done
echo ""
#dvd+rw-mediainfo /dev/"$DEV" | grep Start || exit 1
#echo ""
echo -n "Enter Start Sector Number: "
read SECTOR

echo "CREATING LOOP DEVICE AS ROOT :"
LOOP=`sudo losetup -fP --show \
    -o $(($SECTOR*2048)) \
    /dev/"$DEV"`
echo "DONE"

echo -n "MOUNTING SESSION AS ROOT -> "
sudo mount -t iso9660 -o ro "$LOOP" /home/sprokkel/bluray/ || exit 1
echo ""
echo ""
echo "---------------------"
echo "/home/sprokkel/bluray"
echo "---------------------"
echo ""
ls -ld /home/sprokkel/bluray/*
echo ""
play /usr/share/sounds/freedesktop/stereo/complete.oga > /dev/null 2>&1
echo "SCRIPT COMPLETED -> SESSION SECTOR $SECTOR = MOUNTED."
